site_name: coreason_manifest
theme:
  name: material
nav:
  - Home: index.md
  - Core Definitions:
    - Coreason Agent Manifest (CAM): coreason_agent_manifest.md
    - Runtime Agent Definition: runtime_agent_definition.md
    - Runtime Recipe Definition: runtime_recipe_definition.md
  - Requirements: requirements.md
  - Usage: usage.md
  - Session Management: session_management.md
  - Observability: observability.md
